<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cube Word — Privacy Policy</title>
<style>
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
         max-width: 760px; margin: 2rem auto; padding: 0 1rem; line-height: 1.55;
         color: #1c1c1c; }
  h1 { font-size: 1.7rem; }
  h2 { font-size: 1.2rem; margin-top: 1.8rem; }
  code { background: #f0f0f0; padding: 0 .25em; border-radius: 3px; }
  footer { margin-top: 2.5rem; font-size: .9rem; color: #666; }
</style>
</head>
<body>
<h1>Privacy Policy for Cube Word</h1>
<p><strong>Effective date:</strong> 14 June 2026</p>

<p>This Privacy Policy explains how the mobile game <strong>Cube Word</strong>
("the App", "we", "us"), published by Loafworks, handles information when you
play. By using the App you agree to the practices described here.</p>

<h2>1. Information we collect</h2>
<p>We keep data collection to the minimum needed to run the game and its
optional online features.</p>
<ul>
  <li><strong>Display name.</strong> If you choose to play the Daily Challenge
    and submit a score, the display name you enter is sent to and stored on our
    server so it can appear on the public leaderboard. Entering a name is
    optional; if you leave it blank, scores are submitted as "Anonymous".</li>
  <li><strong>Gameplay data.</strong> When you submit a Daily Challenge score we
    store your score, the time you took, and the words you formed, alongside the
    challenge date, to build the leaderboard.</li>
  <li><strong>Advertising identifiers and related data.</strong> The App shows
    ads using Google AdMob. The Google Mobile Ads SDK may collect your device's
    advertising ID and related device information to serve and measure ads. See
    Google's policies below.</li>
  <li><strong>On-device data.</strong> Game settings, statistics, and your local
    game history are stored only on your device and are not transmitted to us.</li>
</ul>

<h2>2. How we use information</h2>
<ul>
  <li>To operate the Daily Challenge and display public leaderboards.</li>
  <li>To show and measure advertising (via Google AdMob).</li>
  <li>To process the optional "Remove Ads" purchase (via Google Play Billing).</li>
</ul>

<h2>3. Advertising (Google AdMob)</h2>
<p>Advertising is provided by Google AdMob, which acts as a third party and may
use device identifiers for ad personalization, measurement, and fraud
prevention. You can learn more and manage your choices here:</p>
<ul>
  <li>How Google uses data:
    <a href="https://policies.google.com/technologies/partner-sites">policies.google.com/technologies/partner-sites</a></li>
  <li>You can reset or delete your advertising ID, or opt out of ad
    personalization, in your device's Settings &rarr; Google &rarr; Ads.</li>
</ul>
<p>Purchasing "Remove Ads" within the App stops these ads from being shown.</p>

<h2>4. Purchases</h2>
<p>The optional "Remove Ads" purchase is processed entirely by Google Play
Billing. We do not receive or store your payment details; we only store a flag
on your device indicating the purchase was made.</p>

<h2>5. Data sharing</h2>
<p>We do not sell your data. Information is processed by the service providers
that power the App's online features: our backend hosting provider (Supabase)
for the leaderboard, and Google (AdMob for ads, Google Play for purchases).
Leaderboard entries (display name, score, time) are shown publicly to other
players within the App.</p>

<h2>6. Data retention and deletion</h2>
<p>On-device data can be cleared at any time using "Delete Data" in the App's
Options. To request deletion of leaderboard data associated with your display
name from our server, contact us at the email below and we will remove it.</p>

<h2>7. Children</h2>
<p>The App is not directed to children under the age of 13, and we do not
knowingly collect personal information from children. If you believe a child has
provided information, please contact us so we can remove it.</p>

<h2>8. Security</h2>
<p>Data transmitted to our server and to Google's services is sent over
encrypted (HTTPS) connections.</p>

<h2>9. Changes to this policy</h2>
<p>We may update this policy from time to time. Material changes will be
reflected by updating the effective date above.</p>

<h2>10. Contact</h2>
<p>If you have questions or requests regarding this policy or your data, contact:
<br><strong>Loafworks</strong> — <a href="mailto:mrlntheamazing+cubeword@gmail.com">mrlntheamazing+cubeword@gmail.com</a></p>

<footer>
Cube Word is a game by Loafworks.
This privacy policy was generated by AI and reviewed by human.
</footer>
</body>
</html>
